// <auto-generated />
namespace SII.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RelationshipCampusBarriers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RelationshipCampusBarriers));
        
        string IMigrationMetadata.Id
        {
            get { return "201411110515591_RelationshipCampusBarriers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
