// <auto-generated />
namespace SII.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ValidationsAnnouncementAndVisit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidationsAnnouncementAndVisit));
        
        string IMigrationMetadata.Id
        {
            get { return "201411041715460_ValidationsAnnouncementAndVisit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
